name: "compile"

# Run only manually for now
on:
  workflow_dispatch

jobs:
  pre-release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      # ..
      - name: "Checkout repo"
        uses: actions/checkout@v3
      - name: "Substituting Gothic 1 Localizations..."
        run: |
          .scripts/release.sh
      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''
          tag_template: 'dd.mm.yyyy.i'
      - name: "Generate body"
        run: |
          printf "Gothic 1 - Localized\nGothic 1 scripts in all languages hosted on my instance of [weblate](https://weblate.cokoliv.eu/projects/gothic-1/#languages)\nGenerated: %s\n" $(date "+%d-%m-%Y") > body.md
      - name: "Release"
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release/release/*.zip"
          bodyFile: "body.md"
          tag: ${{ steps.generate_release_tag.outputs.next_release_tag }}
          name: Release ${{ steps.generate_release_tag.outputs.next_release_tag }}
