---
name: "release"

# Run only manually for now
on:
  workflow_dispatch

jobs:
  pre-release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      # ..
      - name: "Checkout repo"
        uses: actions/checkout@v3
      - name: "Generate language versions"
        run: |
          ./dacode -t .translations/ -c Scripts/ -i cp1252 -o release/
      - name: "Prepare a release"
        run: |
          #!/bin/bash

          SOURCE_DIR="./release"
          # This is ugly, but works for now :kekw:
          TARGET_DIR="../zipped"

          # Create the target directory if it doesn't exist
          mkdir -p "./zipped"

          # Loop through the directories in the source directory
          for dir in "$SOURCE_DIR"/*; do
          # Check if the item is a directory
          if [ -d "$dir" ]; then
            # Extract the directory name
            dir_name=$(basename "$dir")

            # Change the working directory to the parent directory of the directory to compress
            cd "$(dirname "$dir")"
            # Compress the directory into a zip file
            zip_file="$TARGET_DIR/$dir_name.zip"
            zip -r -q "$zip_file" "$dir_name"
            echo "Compressed $dir_name to $zip_file"
            # Change the working directory back to the original directory
            cd - > /dev/null
          fi
          done
      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''
          tag_template: 'dd.mm.yyyy.i'
      - name: "Generate body"
        run: |
          echo "# Gothic 1 - Localized" > body.md
      - name: "Release"
        uses: ncipollo/release-action@v1
        with:
          artifacts: "zipped/*.zip"
          bodyFile: "body.md"
          tag: ${{ steps.generate_release_tag.outputs.next_release_tag }}
          name: Release ${{ steps.generate_release_tag.outputs.next_release_tag }}
