---
name: "release"

# Run only manually for now
on:
  workflow_dispatch

jobs:
  pre-release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      # ..
      - name: "Checkout repo"
        uses: actions/checkout@v3
      - name: "Generate language versions"
        run: |
          ./dacode -t .translations/ -c Scripts/ -i cp1252 -o release/
      - name: "Prepare a release"
        run: |
          ls release/

      # - uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     automatic_release_tag: "latest"
      #     prerelease: true
      #     title: "Development Build"
      #     files: |
      #       LICENSE.txt
      #       *.jar
